name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:
  workflow_dispatch:

jobs:
  verify-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: 3.41.6

      - name: Verify code formatting
        run: dart format --set-exit-if-changed .

  verify-analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: 3.41.6

      - name: Verify code analysis
        run: dart analyze

  verify-lockfile-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install yq
        uses: dcarbone/install-yq-action@v1
        with:
          version: v4.44.3

      - name: Verify pubspec.lock.json is up to date
        run: |
          yq . pubspec.lock > pubspec.lock.json
          git diff --exit-code -- pubspec.lock.json
